// default package
// Generated 24-jun-2015 16:07:10 by Hibernate Tools 4.0.0
package tablas_Clases;
/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private String nombre;
	private String clave;

	public Usuario() {
	}

	public Usuario(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}
	
	@Override
	public String toString() {
		String res = "";
		res += "Nombre: "+ this.nombre + ", Contraseña: " + this.clave;
		return res;
	}

}
